### ISSUE TITLE
Hitch throwing error on stub.test

### ISSUE THREAD

**Issue by thornomad** [pydanny/cookiecutter-django#339]
Hi there - first time trying `cookiecutter-django` and am just testing it out while I gather my bearings.  Lots of goodies in here!

I am getting an error when I run the `hitch test stub.test` -- I have never run hitch before but as it is a vanilla installation (at this point) I wanted to make sure I wasn't doing anything wrong.  If this is an error that exists outside of this project any help pointing me in the right direction would be great.  

Here is the error I am getting:

    $ hitch test stub.test
    RUNNING TEST Stub 2.7.10
    WARNING: Attempting to work in a virtualenv. If you encounter problems, please install IPython inside the virtualenv.
    Python 3.4.3 (default, Jun  1 2015, 09:58:35)
    Type "copyright", "credits" or "license" for more information.

    IPython 4.0.0 -- An enhanced Interactive Python.
    ?         -> Introduction and overview of IPython's features.
    %quickref -> Quick reference.
    help      -> Python's own help system.
    object?   -> Details about 'object', use 'object??' for extra details.

    Exception occurred in Stub 2.7.10 (/Users/thatsme/Documents/test_project/tests/stub.test) setup.

    [0]: function 'set_up'   ( self.stacktrace[0].ipython() )
      /Users/thatsme/Documents/test_project/tests/engine.py

        20 :         """Ensure virtualenv present, then run all services."""
        21 :         python_package = hitchpython.PythonPackage(
    --> 22 :             python_version=self.preconditions['python_version']
        23 :         )
        24 :         python_package.build()

    [1]: function '__init__'   ( self.stacktrace[1].ipython() )
      /Users/thatsme/Documents/test_project/tests/.hitch/virtualenv/lib/python3.4/site-packages/hitchpython/python_package.py

        47 :             "libreadline6", "libreadline6-dev", "zlib1g-dev", "libxml2", "libxml2-dev",
        48 :             "build-essential", "libssl-dev", "libbz2-dev", "libsqlite3-dev", "sqlite3",
    --> 49 :             "libtool",
        50 :         ])
        51 :         self.bin_directory = bin_directory

    [2]: function 'packages_installed'   ( self.stacktrace[2].ipython() )
      /Users/thatsme/Documents/test_project/tests/.hitch/virtualenv/lib/python3.4/site-packages/unixpackage/api.py

        227 :     """Verify that the list of packages is installed."""
        228 :     if len(packages) > 10:
    --> 229 :         packages_installed(packages[10:])
        230 :         packages = packages[:10]
        231 :     return DISTROS[what_distro_am_i()]["check"](package_list(packages))

    [3]: function 'packages_installed'   ( self.stacktrace[3].ipython() )
      /Users/thatsme/Documents/test_project/tests/.hitch/virtualenv/lib/python3.4/site-packages/unixpackage/api.py

        229 :         packages_installed(packages[10:])
        230 :         packages = packages[:10]
    --> 231 :     return DISTROS[what_distro_am_i()]["check"](package_list(packages))
        232 :
        233 :

    [4]: function '<lambda>'   ( self.stacktrace[4].ipython() )
      /Users/thatsme/Documents/test_project/tests/.hitch/virtualenv/lib/python3.4/site-packages/unixpackage/api.py

        105 :         "sudoinstall": False,
        106 :         "check": lambda packages: len(check_output(
    --> 107 :             ["dpkg", "--status", ] + packages)
        108 :         ) == len(packages),
        109 :     }

    [5]: function 'check_output'   ( self.stacktrace[5].ipython() )
      /Users/thatsme/Documents/test_project/tests/.hitch/virtualenv/lib/python3.4/site-packages/unixpackage/api.py

        44 : def check_output(command, stdout=PIPE, stderr=PIPE):
        45 :     """Re-implemented subprocess.check_output since it is not available < python 2.7."""
    --> 46 :     return Popen(command, stdout=stdout, stderr=stderr).communicate()[0]
        47 :
        48 : def return_code_zero(command):

    builtins.NameError

    name 'Popen' is not defined

    In [1]:

**Comment by crdoconnor** [comment]
Hi,

No, you're not doing anything wrong. This was my mistake. I accidentally pushed some bad code to a few days ago. My apologies.

If you do "hitch install unixpackage" in the tests directory it will upgrade the package and this specific problem should be solved.

If you are using ubuntu or debian it should then work ok. I'm still having teething troubles making the unix-independent software installer handle Mac OS, though, so if you're using that you might want to wait a day or two.

**Comment by pydanny** [comment]
@crdoconnor Can you let us know (or submit a PR), for when `hitch` is ready to go?

@thornomad Glad to have you try out our template. For what it's worth, sometimes these things happen with cookiecutter-django. We like to try exciting new things here, like being a test bed @crdoconnor's awesome work. Thanks for your patience and let us know if you have any questions. :smile:

**Comment by thornomad** [comment]
@crdoconnor I am using a Mac, sorry!  10.10.5.  `hitch install unixpackage` did not fix the issue, as predicted.  On the mac I also had to install `libtool automake cmake` which took a little looking into because `hitch init` was failing.  I've never used Hitch before (py.test, yes) so it's all new to me.

@pydanny - I got here through your book and I like the project layout and goodies ... although starting with such a big footprint is a little overwhelming to me as many of the pieces are new.  Thanks for your quick replies.

**Comment by crdoconnor** [comment]
@thornomad I'm working on the Mac OS X issue now. I should have a solution for you in about 4 or 5 hours. I have been working hard over the last few days on a one step automated platform independent means of installing hitch (i.e. the system takes care of brew installs / apt-get installs / yum installs for you). Other people have also complained about the confusing multitude of packages that needed to be installed. Unfortunately, I released it a few days prematurely and as you can see there's still some teething troubles.

@pydanny As soon as the platform independent installation process is complete and fully tested on Ubuntu, Arch, Debian, Fedora and Mac OS X, I'll submit a PR with the (simplified) instructions. Apologies for breaking your project. I'll be more careful with testing the new releases on different platforms from now on.

**Comment by crdoconnor** [comment]
@thornomad If you run "hitch upgrade" now and try again, hopefully it will work (I just tested it on my Mavericks VM).

**Comment by thornomad** [comment]
@crdoconnor - that fixed it!  I think, at least.  Again: first time user.

End result was an open FireFox window displaying the home page and then a iPython prompt ... is that correct?  Here is the end of the output (after a CTRL-D it said all tests passed):

    [              Hitch] Django Loaded.
    [              Hitch] READY in 5.5 seconds.
    [         Err Django] [22/Sep/2015 12:37:16] "GET / HTTP/1.1" 200 12374
    [         Err Django] [22/Sep/2015 12:37:16] "GET /static/css/project.css HTTP/1.1" 200 530
    [         Err Django] [22/Sep/2015 12:37:16] "GET /static/js/project.js HTTP/1.1" 200 45
    [         Err Django] [22/Sep/2015 12:37:16] "GET /static/debug_toolbar/css/print.css HTTP/1.1" 200 29
    [         Err Django] [22/Sep/2015 12:37:16] "GET /static/debug_toolbar/css/toolbar.css HTTP/1.1" 200 20165
    [         Err Django] [22/Sep/2015 12:37:16] "GET /static/debug_toolbar/js/jquery_pre.js HTTP/1.1" 200 68
    [         Err Django] [22/Sep/2015 12:37:16] "GET /static/debug_toolbar/js/jquery_post.js HTTP/1.1" 200 83
    [         Err Django] [22/Sep/2015 12:37:16] "GET /static/debug_toolbar/js/toolbar.js HTTP/1.1" 200 12506
    [         Err Django] [22/Sep/2015 12:37:16] "GET /static/debug_toolbar/img/ajax-loader.gif HTTP/1.1" 200 404
    WARNING: Attempting to work in a virtualenv. If you encounter problems, please install IPython inside the virtualenv.
    Python 3.4.3 (default, Jun  1 2015, 09:58:35)
    Type "copyright", "credits" or "license" for more information.

    IPython 4.0.0 -- An enhanced Interactive Python.
    ?         -> Introduction and overview of IPython's features.
    %quickref -> Quick reference.
    help      -> Python's own help system.
    object?   -> Details about 'object', use 'object??' for extra details.

    In [1]:

**Comment by crdoconnor** [comment]
Great :)

Yes, that's what you should see. From the IPython prompt you can interact via selenium (self.driver.*), the mock SMTP server (self.services['HitchSMTP'].logs.*), Django (self.services['Django'].manage("shell").run()) and various other stuff.

**Comment by thornomad** [comment]
Great - glad that's settled.  Smile.  I have some more learning to do in the meantime.  Thanks again for the prompt replies and fixes.
